version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: running_db
    environment:
      POSTGRES_USER: running_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: running_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  php:
    build: .  
    container_name: running_php
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html 
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: